#!/usr/bin/env python

import sys
from bitly_api import API


def bitly_shorten(long_url):
    api = API()
    response = api.shorten(long_url)
    if 'error_message' in response:
        return True, response['error_message']
    else:
        return False, response['data']['url']


def usage():
    print "Usage: %s <URL_to_be_shortened>" % sys.argv[0]
    sys.exit(1)


if len(sys.argv) < 2:
    usage()

error, message = bitly_shorten(sys.argv[1])
if error:
    print message
    usage()
print message
